# Generated by Django 4.1.8 on 2023-06-05 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Cardholder")),
                ("number", models.CharField(max_length=16, verbose_name="card number")),
                ("expiration_month", models.CharField(max_length=2, verbose_name="expiration month")),
                ("expiration_year", models.CharField(max_length=4, verbose_name="expiration year")),
                ("cvc", models.CharField(max_length=4, verbose_name="CVC")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cards", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
