# Generated by Django 4.1.8 on 2023-06-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="card",
            constraint=models.UniqueConstraint(fields=("user", "number"), name="unique_user_number"),
        ),
    ]
