# Generated by Django 4.1.8 on 2023-06-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="orderitem",
            name="unique_order_product",
        ),
        migrations.AddField(
            model_name="order",
            name="is_canceled",
            field=models.BooleanField(
                default=False, help_text="Designates whether this order has been canceled.", verbose_name="canceled"
            ),
        ),
    ]
