# Generated by Django 4.1.8 on 2023-06-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_orderitem_unique_order_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_canceled",
        ),
        migrations.RemoveField(
            model_name="order",
            name="is_delivered",
        ),
        migrations.RemoveField(
            model_name="order",
            name="is_returned",
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("returned", "Returned"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=10,
                verbose_name="status",
            ),
        ),
    ]
