# Generated by Django 4.1.8 on 2023-05-23 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_cpf_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name of Company")),
                ("cnpj", models.CharField(max_length=14, unique=True, verbose_name="CNPJ")),
                ("website", models.CharField(blank=True, max_length=255, verbose_name="website")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this company should be treated as active. Unselect this instead of deleting company.",
                        verbose_name="active",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserCompany",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_employee",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user is an employee or just a customer of the company.",
                        verbose_name="employee",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="users", to="users.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
