# Generated by Django 4.1.8 on 2023-05-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_company_usercompany"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="usercompany",
            constraint=models.UniqueConstraint(fields=("user", "company"), name="unique_user_company"),
        ),
    ]
