# Generated by Django 4.1.8 on 2023-06-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="uf",
            field=models.CharField(max_length=2, verbose_name="UF"),
        ),
    ]
