# Generated by Django 4.1.8 on 2023-06-01 14:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0004_usercompany_unique_user_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name of Product")),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)], verbose_name="price"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="descrição")),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this product is approved by the large company.",
                        verbose_name="approved",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electronics", "Electronics"),
                            ("clothing", "Clothing"),
                            ("home", "Início"),
                            ("health_beauty", "Health and Beauty"),
                            ("sports_outdoors", "Sports and Outdoors"),
                            ("books_movies_music", "Books, Movies, and Music"),
                            ("toys_games", "Toys and Games"),
                            ("automotive", "Automotive"),
                            ("furniture_home_decor", "Furniture and Home Decor"),
                            ("office_supplies", "Office Supplies"),
                        ],
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="products", to="users.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="products/", verbose_name="image")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="products.product"
                    ),
                ),
            ],
        ),
    ]
