# Generated by Django 4.1.8 on 2023-06-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="quantity"),
            preserve_default=False,
        ),
    ]
