# Generated by Django 4.1.8 on 2023-06-01 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Cardholder")),
                ("number", models.CharField(max_length=255, verbose_name="Card Number")),
                ("date", models.CharField(max_length=255, verbose_name="Expiration date")),
                ("cvc", models.CharField(max_length=255, verbose_name="CVC")),
            ],
        ),
        migrations.CreateModel(
            name="CardUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "card_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="Fk_Card", to="infouser.card"
                    ),
                ),
                (
                    "user_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Fk_User",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
