# Generated by Django 4.1.8 on 2023-06-01 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("infouser", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cep", models.CharField(max_length=8, verbose_name="CEP")),
                ("uf", models.CharField(max_length=255, verbose_name="UF")),
                ("city", models.CharField(max_length=255, verbose_name="City")),
                ("address1", models.CharField(max_length=255, verbose_name="Address 1")),
                ("address2", models.CharField(blank=True, max_length=255, verbose_name="Address 2")),
                (
                    "id_user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
